### * USER REGISTER
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "username": "marcela",
    "email": "marcela@gmail.com",
    "password": "123456"

}
### * LOGIN USER 
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email": "marcela@gmail.com",
    "password": "123456"
}

### * LOGOUT USER
POST http://localhost:3001/api/auth/logout

### * PETICIONES DE PRODUCTOS
GET http://localhost:3001/api/products


### * POST DE CREAR PRODUCTOS
POST  http://localhost:3001/api/products
Content-Type: application/json

{
    "name": "Taza de One Piece",
    "description": "Taza de One Piece con forma de barril, edicion limitada",
    "price": 5000,
    "stock": 10,
    "imageUrl": "https://res.cloudinary.com/dur3rpnbo/image/upload/v1778281636/tazonOnePiece_ygvotu.webp"

}

### * PUT Actualizar producto
PUT http://localhost:3001/api/products/6a034db28a7f0e806c6bae25
Content-Type: application/json

{
    "description": "Taza de Boku no Hero Academia con foto de varios personajes, edicion limitada"
}

### * GET Obtener un producto por ID
GET http://localhost:3001/api/products/69fe7b6746623fdb16e35788


### * DELETE Eliminar un producto por su id
DELETE http://localhost:3001/api/products/69fe7b6746623fdb16e35788

### * ADD TO CART
POST http://localhost:3001/api/cart/add
Content-Type: application/json

{
    "userId": "6a034643e64bdfb18c61ca2d",
    "productId": "6a0357f67d089305afed414c",
    "quantity": 1
}