### * USER REGISTER
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "username": "marcela",
    "email": "marcela@gmail.com",
    "password": "123456"

}
### * LOGIN USER 
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email": "marcela@gmail.com",
    "password": "123456"
}

### * LOGOUT USER
POST http://localhost:3001/api/auth/logout

### * PETICIONES DE PRODUCTOS
GET http://localhost:3001/api/products


### * POST DE CREAR PRODUCTOS
POST  http://localhost:3001/api/products
Content-Type: application/json

{
    "name": "Taza de One Piece",
    "description": "Taza de One Piece con forma de barril edicion limitada",
    "price": 5000,
    "stock": 10,
    "imageUrl": "https://res.cloudinary.com/dur3rpnbo/image/upload/v1778281636/tazonOnePiece_ygvotu.webp"

}

